### ISSUE TITLE
Object mutation and README vs firestore.rules

### ISSUE THREAD

**Issue by fabyeah** [MichaelSolati/geofirestore-core#1]
This looks like a great package, many thanks! 👍 

I'm currently setting it up and ran into two issues:

1) Are you mutating the object passed to `geocollection.add`? I'm guessing so, as you are adding the `g` key. Can this not be done without mutation, as it is a wrapper I presume? Because I'm getting unexpected behavior with the object i'm passing, namely the sudden appearance of the `g` key.

2) I didn't see the `firestore.rules` file at first. As the README only mentioned the following:

```
interface GeoDocumentData {
  g: {
    geohash: string;
    geopoint: GeoPoint;
  };
  [field: string]: any;
  }
```

I adjusted my security rules accordingly, assuming the `coordinates` would be stripped (it's duplicate data). Is this field used for anything? If not, can this not be removed at the same time that `g` is added? Would be very helpful if the README was more clear about the necessary changes to the security rules.

**Comment by MichaelSolati** [comment]
Just pushed up a fix, it'll be deployed over the weekend.

**Comment by fabyeah** [comment]
OK. Don't know how your fix is going to look, but I think if in the [Data Structure](https://github.com/MichaelSolati/geofirestore-js#data-structure) section of the README the `coordinates` field is added and also a note that security rules should be extended with

```
&& request.resource.data.g.size() == 2
&& request.resource.data.g.geohash is string
&& request.resource.data.g.geopoint is latlng
&& request.resource.data.coordinates is latlng
```

that should be sufficient.
